name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: 'The name to greet'
      age:
        type: number
        required: true
        description: 'The age to greet'
    secrets:
      super-secret:
        
        required: false
        description: 'The super secret to greet'
    outputs:
      reusable-job-output:
        description: 'The output from the reusable job'
        value: ${{ jobs.job1.outputs.reusable-job-output }}
    
    

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      reusable-job-output: ${{ steps.output.outputs.reusable-job-output }}
    steps:
      - id: name
        run: echo "Hello, the name is ${{ inputs.name }}"
      - id: age
        run: echo "Hello, the age is ${{ inputs.age }}"
      - id: output
        run: echo "reusable-job-output= ${{ inputs.name }} is ${{ inputs.age }} years old" >> $GITHUB_OUTPUT
      - id: secret
        run: echo "super-secret=super-secret-value" >> $GITHUB_OUTPUT
      
      