name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: 'The name to greet'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}"
